### PR TITLE
[14.0][ADD] l10n_lu_intrastat_product

### PR DESCRIPTION
**Pull request by rousseldenis**

### CODE REVIEW

**Review by acsonefho — APPROVED** [review]
Code LGTM and already in production since few weeks.

**Comment by acsonefho** [comment]
@rousseldenis maybe a rebase ?

**Comment by sbidoul** [comment]
@rousseldenis I updated the dotfiles, please rebase.

**Comment by rousseldenis** [comment]
Done

**Comment by sbidoul** [comment]
LGTM

/ocabot merge patch

**Pull request merged**
