### PR TITLE
[MIG] l10n_lu_ext from v8 to v10

### PR DESCRIPTION
**Pull request by GillesTephaneMeyomesse**

### CODE REVIEW

**Comment by sbidoul** [comment]
I think we don't need this module in 10.0. Let's concentrate on maintaining the mis builder reports.

@adrienpeiffer what do you think?

**Comment by sbidoul** [comment]
ping @adrienpeiffer

**Comment by adrienpeiffer** [comment]
@sbidoul Totally agree with you. BS and PL should come from MIS BUilder module.

**Comment by sbidoul** [comment]
Ok, I close this. 

Main question is: which menu entry shall we use for community localization features?

**Pull request closed without merging**
